### ISSUE TITLE
图片上传报错

### ISSUE THREAD

**Issue by webchao** [sealice/koa2-ueditor#1]
请问一下"imagePathFormat": "/admin/upload/image/{yyyy}{mm}{dd}/{filename}"中的{filename}上传的时候出现undefined，出现Cannot destructure property `originalname` of 'undefined' or 'null'.请问怎么处理

**Comment by sealice** [comment]
请问使用默认不传参的时候可否上传，还是配置了imagePathFormat后上传图片都报错；
另外不建议保存图片的原文件名，因文件名含有中文或是非法字符可能会造成错误

**Comment by webchao** [comment]
问题解决了，是我把koa-body模块中的上传文件配置的写在了全局app.js里，造成的冲突，后来分开配置就可以了

**Comment by ghost** [comment]
> 问题解决了，是我把koa-body模块中的上传文件配置的写在了全局app.js里，造成的冲突，后来分开配置就可以了

请问分开配置是怎么配置的，我也遇到这个问题了，koa-body和koa2-editor冲突了
@webchao

**Comment by BBQ-zhu** [comment]
解决办法：分开设置，在main，js中引入koaBody但是不配置允许上传文件( app.use(KoaBody()) )，而在对应接口中去设置
router.post('/userImg',KoaBody({multipart: true}),uploads.userImg)
