### ISSUE TITLE
请问如何配置抓取远程图片的action

### ISSUE THREAD

**Issue by shibazijun** [sealice/koa2-ueditor#2]
你好，请问是否可以提供一些action的实例，如：listimage  、catchimage，这两个很有必要。

**Comment by sealice** [comment]
目前没有抓取远程图片的功能，感觉不怎么实用，因为对加了防盗链的网站是抓取不到图片的。

**Comment by shibazijun** [comment]
这个功能是很有用的，如果能完善一下这个功能，咱们这个koa2-ueditor 就更强壮了，或者能否写一个实例，其他功能我们也可以自己去完成了。谢谢！

**Comment by sealice** [comment]
已支持抓取远程图片，请更新

**Comment by shibazijun** [comment]
嗯，牛气！赞一个！

**Comment by sealice** [comment]
谢谢支持
