### ISSUE TITLE
SyntaxError: Unexpected token : 报这个错不知道怎么处理

### ISSUE THREAD

**Issue by zl25822** [sealice/koa2-ueditor#3]

**Comment by sealice** [comment]
koa2需要node版本8.0以上

**Comment by zl25822** [comment]
我用的就是 8.12.0

**Comment by sealice** [comment]
这个错误似乎是使用了当前node版本不支持的api。
能提供更多的信息吗

**Comment by vin957** [comment]
> 这个错误似乎是使用了当前node版本不支持的api。
> 能提供更多的信息吗

我也遇到了同样的问题，Unexpected token : ；我在vue里会报这个错误，但是弄个html demo放到koa的public里可以正常

**Comment by sealice** [comment]
@vin957 能提供重现这个错误的dome吗

**Comment by wangren988888** [comment]
同样的问题,放到vue.js中就会报这个错误.

**Comment by wangren988888** [comment]
![image](https://user-images.githubusercontent.com/19689724/59961430-4d43a080-950a-11e9-83bb-ef1d0b0f86a7.png)
源码的这个位置这样修改一下

**Comment by wangren988888** [comment]
然后还有一个问题是怎么和koa-body中间件兼容使用?

**Comment by sealice** [comment]
> 同样的问题,放到vue.js中就会报这个错误.

这个问题没遇到，是使用vue在开发环境下出现的吗？
是浏览器的控制台报错？还是后台终端报的？

**Comment by sealice** [comment]
> 源码的这个位置这样修改一下

@wangren988888 这样改有什么作用吗？源代码里没有callback这个参数

**Comment by sealice** [comment]
> 然后还有一个问题是怎么和koa-body中间件兼容使用?

@wangren988888 koa-body不是很了解，如果你是要另外写上传接口的话可以使用`upload.js`的方法，具体使用：
```javascript
// uploadController.js

const upload = require('koa2-ueditor/lib/upload')

module.exports = {
	async photoUpload (ctx) {
		try {
			await upload({
				limits: {
					fileSize: 2 * 1024 * 1024
				},
				allowfiles: ['.jpg', '.jpeg', '.png', '.gif'],
			}).single('upfile')(ctx)
			ctx.body = upload.fileFormat(ctx.req.file)
		} catch (err){
			throw new Error(err.message)
		}
	}
}
```

**Comment by vin957** [comment]
能不能不要发给我。。。一直提示新邮件




| |
张健荣
|
|
邮箱：vin957@163.com
|

签名由 网易邮箱大师 定制

在2019年06月22日 20:19，sealice 写道：

然后还有一个问题是怎么和koa-body中间件兼容使用?

@wangren988888 koa-body不是很了解，如果你是要另外写上传接口的话可以使用upload.js的方法，具体使用：

// uploadController.jsconstupload=require('koa2-ueditor/lib/upload')



module.exports= {

	asyncphotoUpload (ctx) {

		try {

			awaitupload({

				limits: {

					fileSize:2*1024*1024

				},

				allowfiles: ['.jpg', '.jpeg', '.png', '.gif'],

			}).single('upfile')(ctx)

			ctx.body=upload.fileFormat(ctx.req.file)

		} catch (err){

			thrownewError(err.message)

		}

	}

}

**Comment by wangren988888** [comment]
> > 同样的问题,放到vue.js中就会报这个错误.
> 
> 这个问题没遇到，是使用vue在开发环境下出现的吗？
> 是浏览器的控制台报错？还是后台终端报的？

是会出现在开发环境中的.浏览器控制台的报错,具体原因是jsonp跨域请求,然而返回到前端的数据结构中没有包含callback的字符串.

**Comment by wangren988888** [comment]
> > 然后还有一个问题是怎么和koa-body中间件兼容使用?
> 
> @wangren988888 koa-body不是很了解，如果你是要另外写上传接口的话可以使用`upload.js`的方法，具体使用：
> 
> ```js
> // uploadController.js
> 
> const upload = require('koa2-ueditor/lib/upload')
> 
> module.exports = {
> 	async photoUpload (ctx) {
> 		try {
> 			await upload({
> 				limits: {
> 					fileSize: 2 * 1024 * 1024
> 				},
> 				allowfiles: ['.jpg', '.jpeg', '.png', '.gif'],
> 			}).single('upfile')(ctx)
> 			ctx.body = upload.fileFormat(ctx.req.file)
> 		} catch (err){
> 			throw new Error(err.message)
> 		}
> 	}
> }
> ```

已经把upload.js的代码搬过来用了,因为以前的上传是用的koa-body实现的,现在这个跟koa-body不兼容,只能去掉koa-body在另外写一个上传.
