### ISSUE TITLE
> 同样的问题,放到vue.js中就会报这个错误.

### ISSUE THREAD

**Issue by wangren988888** [sealice/koa2-ueditor#4]
> 同样的问题,放到vue.js中就会报这个错误.

这个问题没遇到，是使用vue在开发环境下出现的吗？
是浏览器的控制台报错？还是后台终端报的？

_Originally posted by @sealice in https://github.com/sealice/koa2-ueditor/issues/3#issuecomment-504660464_

是因为jsonp导致的, ueditor的config接口默认使用的是jsonp实现的跨域请求,这样的话就需要后段在返回的数据前面加上callback(config),这样返回到前端的数据才能被识别,这个好像是jsonp原理的问题;[callback]这个参数是通过let {action, start = 0, callback} = ctx.query;这一句自己加进来的一个参数,源码中是没有的.

**Comment by sealice** [comment]
@wangren988888 已经修改过来了
