### ISSUE TITLE
koa-body和koa2-ueditor中使用的koa-multer冲突

### ISSUE THREAD

**Issue by ghost** [sealice/koa2-ueditor#5]
如题，用的`koa-body`做的图片上传，
用的`koa2-ueditor`做的富文本，
把`koa-body`中的`mutipart:true`去掉
富文本中的图片上传是好的，
普通的图片上传获取不到上传文件。
加上`mutipart:true`则普通图片上传是好的，
但是ueditor中的上传图片获取不到上传的文件，
这个应该如何解决

**Comment by sealice** [comment]
@ijandc  不要把koa-body作为中间件使用，而是用路由方式应该不会冲突。[用法](https://github.com/dlau/koa-body/blob/master/examples/koa-router.js)

**Comment by ghost** [comment]
> @ijandc 不要把koa-body作为中间件使用，而是用路由方式应该不会冲突。[用法](https://github.com/dlau/koa-body/blob/master/examples/koa-router.js)

好的，我晚上回去试一下~

**Comment by ghost** [comment]
@sealice 搞定了~感谢！
